name: Deploy Component
description: Deploy the trained NER model to Vertex AI Endpoint.
inputs:
- {name: model_dir, type: String}
- {name: project, type: String}
- {name: region, type: String}
- {name: endpoint_name, type: String}
- {name: model_display_name, type: String}
outputs:
- {name: endpoint_info, type: String}
implementation:
  container:
    image: us-east1-docker.pkg.dev/cmlproj2/ner-repo/deploy:latest
    command: [
      "python", "deploy.py",
      "--model-dir", {inputValue: model_dir},
      "--project", {inputValue: project},
      "--region", {inputValue: region},
      "--endpoint-name", {inputValue: endpoint_name},
      "--model-display-name", {inputValue: model_display_name}
    ]
